services:
  sharelatex_app:
    container_name: sharelatex_app
    image: sharelatex/sharelatex:4.2
    depends_on:
      sharelatex_cache:
        condition: service_started
      sharelatex_db:
        condition: service_healthy
    env_file: ${PWD}/env/.env.sharelatex.app
    restart: unless-stopped
    volumes:
      - sharelatex_app_storage:/var/lib/sharelatex
    networks:
      sharelatex:
        aliases:
          - app
          - sharelatex
      localhostings_root:
        aliases:
          - sharelatex
    logging:
      driver: json-file
      options:
        compress: "true"
        max-size: "1024m"
        max-file: "512"
  sharelatex_db:
    container_name: sharelatex_db
    image: mongo:4.0
    env_file: ${PWD}/env/.env.sharelatex.db
    restart: unless-stopped
    volumes:
      - sharelatex_db_data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      sharelatex:
        aliases:
          - db
          - mongo
          - sharelatex_mongo
    logging:
      driver: json-file
      options:
        compress: "true"
        max-size: "1024m"
        max-file: "512"
  sharelatex_cache:
    container_name: sharelatex_cache
    image: redis:5
    env_file: ${PWD}/env/.env.sharelatex.cache
    restart: unless-stopped
    volumes:
      - sharelatex_cache_data:/data
    networks:
      sharelatex:
        aliases:
          - cache
          - redis
          - sharelatex_redis
    logging:
      driver: json-file
      options:
        compress: "true"
        max-size: "1024m"
        max-file: "512"

volumes:
  sharelatex_app_storage:
  sharelatex_db_data:
  sharelatex_cache_data:

networks:
  localhostings_root:
    external: true
  sharelatex:
